### ISSUE TITLE
Redundant using of another one method

### ISSUE THREAD

**Issue by zendet** [undrcrxwn/radzinsky#12]
It's quite hard to understand why did you again using method here:
https://github.com/undrcrxwn/radzinsky/blob/e41d7a0cb259be86945a9924a2fa069c0e5b82be/src/Radzinsky.Application/Extensions/ServiceCollectionExtensions.cs#L116
if you already assigned value in variable (through this method) here:
https://github.com/undrcrxwn/radzinsky/blob/e41d7a0cb259be86945a9924a2fa069c0e5b82be/src/Radzinsky.Application/Extensions/ServiceCollectionExtensions.cs#L114

**Comment by undrcrxwn** [comment]
Thank you for noticing! Gonna fix that just today. Now go fuck yourself.

**Comment by undrcrxwn** [comment]
Thanks for sharing. Fixed.
