### ISSUE TITLE
Ambiguous using of injecting DbContext

### ISSUE THREAD

**Issue by zendet** [undrcrxwn/radzinsky#6]
Here:
https://github.com/undrcrxwn/radzinsky/blob/a1c44812c3a668b85dc7e6b8856d016971f1184b/src/Radzinsky.Application/Services/UpdateHandler.cs#L74 you're just get dbcontext from scope.

But here:
https://github.com/undrcrxwn/radzinsky/blob/a14cdf84f5ec7226f3fefac408411cfc09968e22/src/Radzinsky.Application/Commands/BioCommand.cs#L10 you're getting dbcontext from di.

In my opinion, you should use only **one** method to get necessary service.

**Comment by undrcrxwn** [comment]
Thanks for reporting!
